### ISSUE TITLE
train data?

### ISSUE THREAD

**Issue by yizhiweimengxiangfendoudefeifei** [Andrew-Mackay/Adapting-the-WaveNet-Deep-Learning-Model-for-RADAR-Classification#1]
hello,
  where are your train data? i can't find it, and i can't find the file "gdrive_data_link.env". can you help me? thank you very much.

**Comment by Andrew-Mackay** [comment]
Hello, I apologise but unfortunately I am unable to provide you with the training data as it is not mine to share. It was collected by someone else who allowed me to use it for this project. The .env file is private and was only included in my project submission (this was my honours project).
